// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GalleryItem struct {
	ID         string `json:"id"`
	TaskID     string `json:"task_id"`
	ResultURL  string `json:"resultUrl"`
	ContentURL string `json:"contentUrl"`
	StyleURL   string `json:"styleUrl"`
	CreatedAt  string `json:"createdAt"`
}

type InceptionInfo struct {
	Description  string            `json:"description"`
	ContentLayer string            `json:"contentLayer"`
	StyleLayers  []string          `json:"styleLayers"`
	AllLayers    []*InceptionLayer `json:"allLayers"`
}

type InceptionLayer struct {
	Name string `json:"name"`
	Role string `json:"role"`
}

type ModelInfo struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Layers      []string `json:"layers"`
}

type Mutation struct {
}

type Query struct {
}

type StyleImage struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	ThumbnailPath string `json:"thumbnailPath"`
}

type StyleTransferInput struct {
	ContentImagePath string  `json:"contentImagePath"`
	StyleImageID     string  `json:"styleImageId"`
	ContentWeight    float64 `json:"contentWeight"`
	StyleWeight      float64 `json:"styleWeight"`
	Iterations       int32   `json:"iterations"`
}

type StyleTransferResponse struct {
	TaskID string `json:"taskId"`
	Status string `json:"status"`
}

type StyledFrame struct {
	TaskID      string `json:"taskId"`
	StyledImage string `json:"styledImage"`
}
