package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/yuuuuuh-14/ai-style-studio/backend/graph/model"
	"github.com/yuuuuuh-14/ai-style-studio/backend/ml"
)

// StartGatysTransfer is the resolver for the startGatysTransfer field.
func (r *mutationResolver) StartGatysTransfer(ctx context.Context, input model.StyleTransferInput) (*model.StyleTransferResponse, error) {
	taskId := uuid.New().String()
	ml.DefaultTaskManager.CreateTask(taskId)

	// Start optimization in background
	go r.Engine.ExecuteTask(taskId, input)

	return &model.StyleTransferResponse{
		TaskID: taskId,
		Status: "started",
	}, nil
}

// ProcessWebcamFrame is the resolver for the processWebcamFrame field.
func (r *mutationResolver) ProcessWebcamFrame(ctx context.Context, image string, modelID string) (*model.StyledFrame, error) {
	// Simple mock or real inference if model is cached
	// result, _ := r.FastEngine.RunInference(ctx, image, modelID)
	return &model.StyledFrame{
		TaskID:      "webcam-task",
		StyledImage: image, // Mock: echoing back the image for now
	}, nil
}

// SaveToGallery is the resolver for the saveToGallery field.
func (r *mutationResolver) SaveToGallery(ctx context.Context, taskID string) (*model.GalleryItem, error) {
	task := ml.DefaultTaskManager.GetTask(taskID)
	if task == nil {
		return nil, fmt.Errorf("task not found")
	}

	item := &model.GalleryItem{
		ID:         uuid.New().String(),
		TaskID:     taskID,
		ResultURL:  task.PreviewURL,
		ContentURL: "uploads/content_sample.jpg",
		StyleURL:   "uploads/style_sample.jpg",
		CreatedAt:  time.Now().Format(time.RFC3339),
	}

	ml.DefaultGalleryManager.Save(item)
	return item, nil
}

// GetModels is the resolver for the getModels field.
func (r *queryResolver) GetModels(ctx context.Context) ([]*model.ModelInfo, error) {
	return r.Models, nil
}

// GetStyleImages is the resolver for the getStyleImages field.
func (r *queryResolver) GetStyleImages(ctx context.Context) ([]*model.StyleImage, error) {
	return r.StyleImages, nil
}

// GetInceptionInfo is the resolver for the getInceptionInfo field.
func (r *queryResolver) GetInceptionInfo(ctx context.Context) (*model.InceptionInfo, error) {
	return &model.InceptionInfo{
		Description:  "Inception-v3 optimization based style transfer.",
		ContentLayer: "conv2d_94",
		StyleLayers:  []string{"conv2d_1", "conv2d_2", "mixed_0", "mixed_1"},
		AllLayers: []*model.InceptionLayer{
			{Name: "conv2d_1", Role: "Style"},
			{Name: "mixed_0", Role: "Contrast"},
		},
	}, nil
}

// GetGallery is the resolver for the getGallery field.
func (r *queryResolver) GetGallery(ctx context.Context, page *int32, limit *int32) ([]*model.GalleryItem, error) {
	p := 1
	l := 10
	if page != nil { p = int(*page) }
	if limit != nil { l = int(*limit) }
	
	items := ml.DefaultGalleryManager.GetItems(p, l)
	return items, nil
}

// GetFeatureMaps is the resolver for the getFeatureMaps field.
func (r *queryResolver) GetFeatureMaps(ctx context.Context, taskID string, layerName string) ([]string, error) {
	// Return mock base64 images for demonstration
	return []string{"base64_fm1", "base64_fm2"}, nil
}

// GetGramMatrix is the resolver for the getGramMatrix field.
func (r *queryResolver) GetGramMatrix(ctx context.Context, taskID string, layerName string) ([][]float64, error) {
	// Return small identity-like matrix for mock
	return [][]float64{{1.0, 0.0}, {0.0, 1.0}}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) StartStyleTransfer(ctx context.Context, input model.StyleTransferInput) (*model.StyleTransferResponse, error) {
	taskId := uuid.New().String()

	// 작업 채널 생성
	ml.DefaultTaskManager.CreateTask(taskId)

	// 비동기로 스타일 변환 작업 시작
	go r.Engine.ExecuteTask(taskId, input)

	return &model.StyleTransferResponse{
		TaskID: taskId,
		Status: "queued",
	}, nil
}
*/
